/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Comments: typeof import('./components/Comments/index.vue')['default']
    Container: typeof import('./components/Container/index.vue')['default']
    HotBlog: typeof import('./components/HotBlog/index.vue')['default']
    ImageWaterfall: typeof import('./components/ImageWaterfall/index.vue')['default']
    Loading: typeof import('./components/Loading/index.vue')['default']
    NetWorkError: typeof import('./components/NetWorkError/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagsCloud: typeof import('./components/TagsCloud/index.vue')['default']
    UserCard: typeof import('./components/UserCard/index.vue')['default']
  }
}
